### DISCUSSION TITLE
Nextcloud Docker Add new language

### DISCUSSION THREAD

**Discussion by lesu1** [R0Wi-DEV/workflow_ocr#135] [Q&A] [answered]
Hi,
Could you please guide me on how to add a new language? (Estonian in my case).
According to Tesseract docs: https://github.com/tesseract-ocr/tesseract/blob/main/doc/tesseract.1.asc#languages

est (Estonian) code for the language.

I have installed Nextcloud with Docker. I used commands:
```
docker-compose exec nextcloud apt -y update
docker-compose exec nextcloud apt -y install tesseract-ocr-est
```

I restarted my docker container, and language did not appear under the list of available languages. I assume I'm missing something.

I believe after an Image update, I will need to do it all around, right? 

Appreciate any help you can provide.

**Comment by R0Wi** [comment]
Hi, so basically you're running into the same issue like mentioned in https://github.com/R0Wi/workflow_ocr/issues/119. The current dropdown list is hardcoded and does not receive the installed languages from the backend system. For now i will add the `est`-option for you, in the future it could be a feature to read the installed languages and keep the UI up to date with it.

Just another hint: if you restart a container by `docker-compose down && docker-compose up -d` the container will be destroyed and all installed packages will be lost. So to persist any packages and other system modifications i'd recommend to use a custom `Dockerfile` like described [here](https://github.com/R0Wi/workflow_ocr#docker-based-setup).

**Comment by lesu1** [comment]
Hi, thank you R0Wi for the detailed answer and for the est-option in the backend. Waiting for the update.

As for the docker-compose, actually, I've just restarted the Nextcloud container from Portainer, so it shouldn't pull the new image. I think.

It seems that I need to learn something new with custom Dockerfile, I will put this on my list for the future.  Meanwhile, for me, I believe it will be easier to install the package with one/few commands after the image update.

Thanks again, I appreciate your fast turnaround.

**Reply by R0Wi** [reply]
Update is on the go :rocket: 

Well one of the key concepts of Docker is that containers are most likely "stateless". Every kind of state you want to apply has to be persisted either by volumes or by extending a base image. So speaking from my experience if you have to use additional libraries in your NC container, i'd build a custom image and use that one.

For NC you could basically go like this:

1. Adjust your `docker-compose.yml`-file to have a `build`-section pointing to your `Dockerfile` and make sure you use a custom image name to force Docker to build your image
```yml
version: '2'

volumes:
  nextcloud:
  db:

services:
  db:
    image: mariadb
    restart: always
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_PASSWORD=
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud

  app:
    # Adjust the image name to your needs, this will be branded into your custom image
    image: nextcloud-24-custom
    restart: always
    # Add this section here:
    build:
      dockerfile: ./Dockerfile
    ports:
      - 8080:80
    links:
      - db
    volumes:
      - nextcloud:/var/www/html
    environment:
      - MYSQL_PASSWORD=
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=db
```
2. Add a `Dockerfile` with the following content inside the same folder:
```dockerfile
FROM nextcloud:24-apache

RUN    apt-get update \
    && apt-get install -y make ocrmypdf tesseract-ocr-eng tesseract-ocr-est \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* /usr/share/doc/*
```
3. Build your image with `docker-compose build`
4. Run the image as usual with `docker-compose up -d`

If you want to have the base image version as a variable inside a `.env`-file, you could go with something like https://github.com/R0Wi/workflow_ocr#docker-based-setup, but this makes it slighly more complicated.

**Comment by R0Wi** [comment, marked as answer]
**Summary**

For a custom NC docker image, you could basically go like this:

1. Adjust your `docker-compose.yml`-file to have a `build`-section pointing to your `Dockerfile` and make sure you use a custom image name to force Docker to build your image
```yml
version: '2'

volumes:
  nextcloud:
  db:

services:
  db:
    image: mariadb
    restart: always
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_PASSWORD=
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud

  app:
    # Adjust the image name to your needs, this will be branded into your custom image
    image: nextcloud-24-custom
    restart: always
    # Add this section here:
    build:
      dockerfile: ./Dockerfile
    ports:
      - 8080:80
    links:
      - db
    volumes:
      - nextcloud:/var/www/html
    environment:
      - MYSQL_PASSWORD=
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=db
```
2. Add a `Dockerfile` with the following content inside the same folder:
```dockerfile
FROM nextcloud:24-apache

RUN    apt-get update \
    && apt-get install -y make ocrmypdf tesseract-ocr-eng tesseract-ocr-est \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* /usr/share/doc/*
```
3. Build your image with `docker-compose build`
4. Run the image as usual with `docker-compose up -d`

If you want to have the base image version as a variable inside a `.env`-file, you could go with something like https://github.com/R0Wi/workflow_ocr#docker-based-setup, but this makes it slighly more complicated.
